version: 2.1

jobs:
  build: # workflow name from below
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git # need a docker image that has the docker commands built in in order to run personal docker containers.
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD # circle/ci environment variables
    steps:
      - checkout
      - setup_remote_docker
      - run:
           name: Build Docker container
           command: docker build -t lua .

      #  https://circleci.com/docs/2.0/building-docker-images/ ; look for "Mounting Folders" to see why I did it this way.
      - run:
           name: Copy files to container
           command: |
            docker create -v /app/src --name lua_container lua
            docker container cp /app/. lua_container:/app/src

      - run:
           name: Run tests
           command: |
            docker run --volumes-from lua_container -it lua /bin/bash -c "busted /app/src/coding_questions/data_structures"

# Orchestrate or schedule a set of jobs
workflows:
  build_and_test:
    jobs:
      - build
